== Trademarks

Red Hat^®^, Red Hat^®^ Enterprise Linux, the Shadowman logo, JBoss^®^, MetaMatrix, Fedora,
the Infinity Logo, and RHCE^®^ are trademarks of Red Hat, Inc., registered in the
United States and other countries.

Linux^®^ is the registered trademark of Linus Torvalds in the United States and
other countries.

Java™ is a registered trademark of Oracle and/or its affiliates.

XFS^®^ is a trademark of Silicon Graphics International Corp. or its subsidiaries
in the United States and/or other countries.

MySQL is a registered trademark of MySQL AB in the United States, the European
Union and other countries.

Node.js is an official trademark of Joyent. Red Hat Software Collections is not
formally related to or endorsed by the official Joyent Node.js open source or
commercial project.

The OpenStack Word Mark and OpenStack Logo are either registered trademarks/service
marks or trademarks/service marks of the OpenStack Foundation, in the United
States and other countries and are used with the OpenStack Foundation's permission.
We are not affiliated with, endorsed or sponsored by the OpenStack Foundation, or
the OpenStack community.

UNIX is a registered trademark of The Open Group.

Docker and the Docker logo are trademarks or registered trademarks of
Docker, Inc.

Intel, the Intel logo and Xeon are registered trademarks of Intel Corporation or
its subsidiaries in the United States and other countries.

All other trademarks are the property of their respective owners.
